options:
 
  http_proxy_port:
    type: int
    default: 8123
    description: "HTTP proxy port"

  socks5_proxy_port:
    type: int
    default: 9050
    description: "SOCKS proxy port"

  relay:
    type: boolean
    default: true
    description: "Enable Tor relay."

  relay_port:
    type: int
    default: 9001
    description: "Port to advertise for incoming Tor connections."

  relay_nickname:
    type: string
    default: ""
    description: "Nickname to give this relay node."

  relay_exit_policy:
    type: string
    default: "reject *:*"
    description: "Exit policy for the relay node."
