#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

TS=$(date '+%Y%m%d%H%M%S')

#######################################################################
### Construct tor config

# Back up existing torrc
cp /etc/tor/torrc /etc/tor/torrc.${TS}

cat >/etc/tor/torrc.d/00-listen <<EOF
SocksPort $(unit-get private-address):$(config-get socks5-proxy-port)
SocksPort 127.0.0.1:$(config-get socks5-proxy-port)
EOF

if [ $(config-get relay | tr A-Z a-z) = "true" ]; then
	NICKNAME=$(config-get nickname)
	if [ -z "$NICKNAME" ]; then
		NICKNAME=$(dd if=/dev/urandom of=/dev/stdout count=1 bs=1k | sha1sum | awk '{print $1}')
	fi

	cat >/etc/tor/torrc.d/01-relay <<EOF
ORPort $(unit-get public-address):$(config-get relay-port)
Address $(unit-get public-address)
Nickname $NICKNAME
ExitPolicy $(config-get relay-exit-policy)
EOF
else
	>/etc/tor/torrc.d/01-relay
fi

cat /etc/tor/torrc.d/* >/etc/tor/torrc

service tor restart

#######################################################################
### Construct polipo config

# Back up existing polipo config
cp /etc/polipo/config /etc/polipo/config.${TS}

cat >/etc/polipo/config.d/00-listen <<EOF
proxyAddress = "$(unit-get private-address)"
proxyPort = $(config-get http-proxy-port)
allowedClients = 127.0.0.1, $(unit-get private-address | sed 's/[0-9]+$/\.0/')/24
socksParentProxy = "127.0.0.1:$(config-get socks5-proxy-port)"
socksProxyType = socks5
EOF

cat /etc/polipo/config.d/* >/etc/polipo/config

service polipo restart

#######################################################################
