#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

service polipo restart
service tor restart

if [ -n "$(config-get relay-port)" ]; then
	open-port $(config-get relay-port)
fi
