#!/bin/bash -e

# Disable TCP timestamps
echo 0 > /proc/sys/net/ipv4/tcp_timestamps

# Block ICMP timestamps
iptables -A INPUT -p icmp --icmp-type timestamp-request -j DROP
iptables -A OUTPUT -p icmp --icmp-type timestamp-reply -j DROP

