- hosts: all
  tasks:

# hidden-website relation
#
    - name: Add hidden website
      shell: echo "$(relation-get hostname):$(relation-get port)" > /etc/tor/hidden-website
      tags:
        - hidden-website-joined
        - hidden-website-changed

    - name: Remove hidden website
      shell: rm /etc/tor/hidden-website
      tags:
        - hidden-website-broken
        - hidden-website-departed

# config-changed tasks
#
    - name: Generate nickname
      shell: ../files/generate_nickname
      register: generated_nickname_result
      tags:
        - config-changed

    - name: Set public address
      shell: "unit-get public-address"
      register: unit_public_address_result
      tags:
        - config-changed

    - name: Set private address
      shell: "unit-get private-address"
      register: unit_private_address_result
      tags:
        - config-changed

    - name: Set private network
      shell: echo $(unit-get private-address | sed 's/[0-9]+$/\\.0/')/24
      register: unit_private_network_result
      tags:
        - config-changed

    - name: Set hidden-website, if any
      shell: cat /etc/tor/hidden-website || true
      register: hidden_website_result
      tags:
        - config-changed

    - name: Configure Tor
      template: src=../torrc.j2 dest=/etc/tor/torrc 
      tags:
        - config-changed 

    - name: Configure Polipo
      template: src=../polipo_config.j2 dest=/etc/polipo/config 
      tags:
        - config-changed

    - name: Restart services
      service: name={{ item }} state=restarted
      with_items:
        - tor
        - polipo
      tags:
        - config-changed

# install & upgrade tasks
#
    - name: Add torproject.org repository
      apt_repository: repo='deb http://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main' state=present
      tags:
        - install

    - name: Add torproject.org package signing key
      apt_key: keyserver=pool.sks-keyservers.net id=886DDD89 state=present
      tags:
        - install

    - name: Install packages
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - deb.torproject.org-keyring
        - tor
        - polipo
      tags:
        - install
        - upgrade-charm

    - name: Create hidden service dir
      shell: mkdir -p /var/lib/tor/hidden_service; chown -R debian-tor /var/lib/tor/hidden_service
      tags:
        - install

# start & stop
#
    - name: Disable TCP & ICMP timestamping
      shell: ../files/disable_timestamping
      tags:
        - start

    - name: Start services
      service: name={{ item }} state=started
      with_items:
        - tor
        - polipo
      tags:
        - start

    - name: Stop services
      service: name={{ item }} state=stopped
      with_items:
        - tor
        - polipo
      tags:
        - stop

